Do not assume a constraint has columns
When specifying a constraint like:

CREATE TABLE demo (
    i integer,
    CONSTRAINT demo_check CHECK (false) NO INHERIT
);

The to_map function raised the following error:

TypeError: 'NoneType' object is not iterable

As creating a CHECK constraint which does not reference a
column is valid, and sometimes useful (as the above is
useful in inherited tables) ensure we only fill columns if
columns can be found.